# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='owner',
        ),
        migrations.AddField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
