# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0002_auto_20171128_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
