# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0004_modelformfailurehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='photo',
            field=models.ImageField(default='', upload_to='unions'),
        ),
    ]
