# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unionapp', '0005_union_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
    ]
