# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171128_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('birth_date', models.DateField(blank=True)),
                ('sent', models.BooleanField(default=False)),
                ('redeemed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
